# Generated by Django 4.0.3 on 2022-04-06 02:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(2030),
                            django.core.validators.MinValueValidator(1900),
                        ]
                    ),
                ),
                ("varietal", models.CharField(max_length=75)),
                ("location", models.CharField(max_length=70)),
                ("description", models.TextField()),
                ("image", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
