# Generated by Django 4.0.3 on 2022-04-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wines", "0002_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consultant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("comment", models.TextField()),
            ],
        ),
    ]
