# Generated by Django 4.0.3 on 2022-04-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0003_consultant'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='techsheet',
            field=models.URLField(blank=True),
        ),
    ]
